name: publish
run-name: "${{ format('release {0}', inputs.version || 'preview') }}"

on:
  push:
    branches:
      - dev
  workflow_dispatch:
    inputs:
      version:
        description: "Override version (optional)"
        required: false
        type: string

concurrency: ${{ github.workflow }}-${{ github.ref }}-${{ inputs.version }}

permissions:
  contents: write

jobs:
  version:
    runs-on: ubuntu-latest
    if: github.repository == 'DigitainIT/opencode'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup-bun

      - id: version
        run: |
          ./script/version.ts
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENCODE_VERSION: ${{ inputs.version }}
          GH_REPO: ${{ github.repository }}
    outputs:
      version: ${{ steps.version.outputs.version }}
      release: ${{ steps.version.outputs.release }}
      tag: ${{ steps.version.outputs.tag }}
      repo: ${{ steps.version.outputs.repo }}

  build-cli:
    needs: version
    runs-on: ubuntu-latest
    if: github.repository == 'DigitainIT/opencode'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-tags: true

      - uses: ./.github/actions/setup-bun

      - name: Build
        id: build
        run: |
          ./packages/opencode/script/build.ts
        env:
          OPENCODE_VERSION: ${{ needs.version.outputs.version }}
          OPENCODE_RELEASE: ${{ needs.version.outputs.release }}
          OPENCODE_CONSOLE_URL: https://oc-dev.digitain.ai
          GH_REPO: ${{ needs.version.outputs.repo }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/upload-artifact@v4
        with:
          name: opencode-cli
          path: |
            packages/opencode/dist/opencode-darwin*
            packages/opencode/dist/opencode-linux*

      - uses: actions/upload-artifact@v4
        with:
          name: opencode-cli-windows
          path: packages/opencode/dist/opencode-windows*

    outputs:
      version: ${{ needs.version.outputs.version }}

  publish-npm:
    needs:
      - version
      - build-cli
    runs-on: ubuntu-latest
    if: github.repository == 'DigitainIT/opencode'
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-bun

      - uses: actions/setup-node@v4
        with:
          node-version: "24"
          registry-url: "https://registry.npmjs.org"

      - uses: actions/download-artifact@v4
        with:
          name: opencode-cli
          path: packages/opencode/dist

      - uses: actions/download-artifact@v4
        with:
          name: opencode-cli-windows
          path: packages/opencode/dist

      - name: Publish to npm
        run: ./packages/opencode/script/publish.ts
